Areas/Admin/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.Domain;

namespace App.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DocumentsController : Controller
    {
        private readonly AppDbContext _context;

        public DocumentsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Documents
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Documents.Include(d => d.AppUser).Include(d => d.Patient);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Admin/Documents/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.AppUser)
                .Include(d => d.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // GET: Admin/Documents/Create
        public IActionResult Create()
        {
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["PatientId"] = new SelectList(_context.Patients, "Id", "Id");
            return View();
        }

        // POST: Admin/Documents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImagePath,DocumentType,AppUserId,PatientId")] Document document)
        {
            if (ModelState.IsValid)
            {
                document.Id = Guid.NewGuid();
                _context.Add(document);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", document.AppUserId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "Id", "Id", document.PatientId);
            return View(document);
        }

        // GET: Admin/Documents/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents.FindAsync(id);
            if (document == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", document.AppUserId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "Id", "Id", document.PatientId);
            return View(document);
        }

        // POST: Admin/Documents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,ImagePath,DocumentType,AppUserId,PatientId")] Document document)
        {
            if (id != document.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(document);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocumentExists(document.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", document.AppUserId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "Id", "Id", document.PatientId);
            return View(document);
        }

        // GET: Admin/Documents/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.AppUser)
                .Include(d => d.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // POST: Admin/Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var document = await _context.Documents.FindAsync(id);
            _context.Documents.Remove(document);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DocumentExists(Guid id)
        {
            return _context.Documents.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Controllers/PatientsController.cs
using App.Domain;
using App.Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace App.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PatientsController : Controller
    {

        private readonly DataManager _dataManager;
        public PatientsController(DataManager dataManager)
        {
            this._dataManager = dataManager;
        }

        public IActionResult Index()
        {
           return View(_dataManager.Patients.GetPatients());
        }

        public IActionResult Edit(Guid Id)
        {
            var Patient = _dataManager.Patients.GetPatientById(Id);
            return View(Patient);
        }
        [HttpPost]
        public IActionResult Edit(Patient model)
        {
            if(ModelState.IsValid)
            {
                _dataManager.Patients.SavePatient(model);
            }
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Patient model)
        {
            if(ModelState.IsValid)
            {
                Patient NewPatient = new Patient{Name = model.Name, BirthDate = model.BirthDate, PhoneNumber = model.PhoneNumber,
                ImgPath = model.ImgPath};
            _dataManager.Patients.SavePatient(NewPatient);
                return RedirectToAction("Index","Patients");
            }
            return View(model);            
        }

    }
}

Areas/Admin/Controllers/UsersController.cs
using App.Areas.Admin.Models.ViewModels;
using App.Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace App.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsersController : Controller
    {
        readonly UserManager<AppUser> _userManager;

        public UsersController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppUser user = new AppUser { Login = model.Login, UserName = model.UserName };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, UserName = user.UserName, PhoneNumber = user.PhoneNumber };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppUser user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Id = model.Id;
                    user.UserName = model.UserName;
                    user.PhoneNumber = model.PhoneNumber;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index","Home");
        }
    }
}

Areas/Admin/Views/Patients/Create.cshtml
@model Patient
@{
    ViewBag.Title = "Cтворення користувача";
}
@*
  Name
  Photo
  BirthDate
  PhoneNumber
*@
<form asp-action="Edit" asp-controller="Patients">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="ImgPath" class="control-label">Photo</label>
        <input type="text" asp-for="ImgPath" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="BirthDate" class="control-label">BirthDate</label>
        <input type="Date" asp-for="BirthDate" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">PhoneNumber</label>
        <input type="tel" asp-for="PhoneNumber" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
    </div>
</form>

Areas/Admin/Views/Patients/Edit.cshtml
@model Patient
@{
    ViewBag.Title = "Редагування користувача " + Model.Name;
}
@*
  Name
  Photo
  BirthDate
  PhoneNumber
*@
<form asp-action="Edit" asp-controller="Patients">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
        <input type="hiden" asp-for="DateAdded" />
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="ImgPath" class="control-label">Photo</label>
        <input type="text" asp-for="ImgPath" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="BirthDate" class="control-label">BirthDate</label>
        <input type="Date" asp-for="BirthDate" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">PhoneNumber</label>
        <input type="tel" asp-for="PhoneNumber" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
    </div>
</form>

Areas/Admin/Views/Patients/Index.cshtml
@model IEnumerable<Patient>

<table class="table">
    <tr>
        <th>Фото</th>
        <th>Ім`я</th>
        <th>Дата народження</th>
        <th>Номер телефону</th>
        <th></th> @* for edit\delete buttons*@
       
    </tr>
    @foreach (var patient in Model)
    {
        <tr>
            @if(patient.ImgPath == null)
            {
                <td><img src="~/images/NoPhoto.png"/></td>
            }
            else
            {
                string n = patient.Name;
                <td><img src="~/images/n/Photo.png"></td>
            }
            <td>@patient.Name</td>
            <td>@patient.BirthDate.ToString("dd/MM/yyyy")</td>
            <td>@patient.PhoneNumber</td>
            <td>
                <form asp-controller="Users" asp-action="Delete" asp-route-id="@patient.Id" method="post">
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@patient.Id">Редагувати</a>
                    <a class="btn btn-sm btn-primary" asp-action="GetPatientDocuments" asp-controller="Documents" asp-route-id="@patient.Id">Документи</a>
                    <button type="submit" class="btn btn-sm btn-danger">
                        Видалити
                    </button>
                </form>
            </td>
        </tr>
    }
</table>